=== eurocontrol-ladr/ladrApplicationMessages/schemas/distressEventUploadValidationMessage/ladrmessage/LadrApplicationMessage.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0" xmlns:ladr="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fx="http://www.fixm.aero/flight/4.2" xmlns:fb="http://www.fixm.aero/base/4.2" elementFormDefault="qualified" version="0.0.1">
	<xs:annotation>
		<xs:documentation>The profile corresponding to the DistressEventUploadValidationMessage. Copyright EUROCONTROL</xs:documentation>
	</xs:annotation>
	<xs:element name="LadrApplicationMessage" type="ladr:LadrApplicationMessageType">
		<xs:annotation>
			<xs:documentation>The LADR Message element is an entry point to the LADR information exchange model.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="ContributorCodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]){3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DateTimeUtcType">
		<xs:restriction base="xs:dateTime">
			<xs:pattern value="-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?|(24:00:00(\.0+)?))Z"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LadrApplicationMessageTypeType">
		<xs:annotation>
			<xs:documentation>A message sent from a LADR user to the LADR, acknowledging the receipt of a distress event notification message.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DISTRESS_EVENT_UPLOAD_VALIDATION_MESSAGE">
				<xs:annotation>
					<xs:documentation>A message from the LADR to a LADR contributor indicating whether a distress event upload message is valid against it associated schema.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LadrApplicationMessageValidationStatusType">
		<xs:annotation>
			<xs:documentation>A code indicating whether the LADR Application Message has successfully passed schema validation.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="NOT_VALID">
				<xs:annotation>
					<xs:documentation>The LADR Application Message does not validate against the applicable schemas.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="VALID">
				<xs:annotation>
					<xs:documentation>The LADR Application Message validates against the applicable schemas.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="RestrictedUniversallyUniqueIdentifierType">
		<xs:annotation>
			<xs:documentation>Helper type for restrictions on UniversallyUniqueIdentifier</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="DistressEventType">
		<xs:annotation>
			<xs:documentation>The collection of autonomous distress tracking data about a given flight in distress phase.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="identifier" type="ladr:UniversallyUniqueIdentifierType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The identifier of the distress event.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="contributorCode" type="ladr:ContributorCodeType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>A code identifying [the LADR contributor ???], which enables to establish contributor domain for data validation.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LadrApplicationMessageMetadataType">
		<xs:annotation>
			<xs:documentation>Information about the LADR application message.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="identifier" type="ladr:UniversallyUniqueIdentifierType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The identifier of the message.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timestamp" type="ladr:DateTimeUtcType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The time and date that the communication was sent.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="receiptTime" type="ladr:DateTimeUtcType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Date and time of receipt.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="type" type="ladr:LadrApplicationMessageTypeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The type of LADR Application Message.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="validationStatus" type="ladr:LadrApplicationMessageValidationStatusType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>A code indicating whether the LADR Application Message has successfully passed schema validation.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="referencedMessageIdentifier" type="ladr:UniversallyUniqueIdentifierType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The identifier of the LADR Application Message that this message refers to.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="tunv" type="ladr:DateTimeUtcType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Date and time at which the LADR system has logged the distress event upload message as invalid.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="tval" type="ladr:DateTimeUtcType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Date and time at which the LADR system has validated the distress event upload message against its schema.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LadrApplicationMessageType">
		<xs:annotation>
			<xs:documentation>A message used to exchange information between the LADR and its contributors and users.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="metadata" type="ladr:LadrApplicationMessageMetadataType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Information about the LADR application message.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="distressEvent" type="ladr:DistressEventType" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The distress event that the LADR application message is about.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UniversallyUniqueIdentifierType">
		<xs:annotation>
			<xs:documentation>A 128-bit number used, with a high probability, to uniquely identify information in computer systems.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="ladr:RestrictedUniversallyUniqueIdentifierType">
				<xs:attribute name="codeSpace" use="required" fixed="urn:uuid" type="xs:string">
					<xs:annotation>
						<xs:documentation>Code Space of the UUID</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== eurocontrol-ladr/ladrApplicationMessages/samples/distressEventUploadValidationMessage/DistressEventUploadValidationMessage_sample_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 (x64) (http://www.altova.com)-->
<ladr:LadrApplicationMessage xmlns:fb="http://www.fixm.aero/base/4.2" xmlns:fx="http://www.fixm.aero/flight/4.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ladr="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0" xsi:schemaLocation="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0 ../../schemas/distressEventUploadValidationMessage/ladrmessage/LadrApplicationMessage.xsd">
	<ladr:metadata>
	    <!--TO BE DISCUSSED :  identifier of a message -->		
		<ladr:identifier codeSpace="urn:uuid">7f79eaf3-3053-48b6-b699-293d54ee0d67</ladr:identifier>
		<!--TO BE DISCUSSED :  temporality associated with LADR messages and what needs to be exchanged -->	
		<ladr:timestamp>2022-01-19T06:00:15Z</ladr:timestamp>
		<ladr:receiptTime>2022-01-19T06:00:15Z</ladr:receiptTime>		
		<ladr:type>DISTRESS_EVENT_UPLOAD_VALIDATION_MESSAGE</ladr:type>
		<ladr:validationStatus>NOT_VALID</ladr:validationStatus>
		<ladr:referencedMessageIdentifier codeSpace="urn:uuid">eca23996-df29-4ee2-a886-bf8f150a75a4</ladr:referencedMessageIdentifier>
		<ladr:tunv>2022-01-19T06:00:13Z</ladr:tunv>
		<ladr:tval>2022-01-19T06:00:14Z</ladr:tval>
	</ladr:metadata>
</ladr:LadrApplicationMessage>
