=== eurocontrol-ladr/ladrApplicationMessages/schemas/ladrEventMessage/ladrmessage/LadrMessage.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ladr="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0" xmlns:fb="http://www.fixm.aero/base/4.2" xmlns:fx="http://www.fixm.aero/flight/4.2" elementFormDefault="qualified" version="0.0.1">
	<xs:annotation>
		<xs:documentation>The profile corresponding to the LadrEventMessage. Copyright EUROCONTROL</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.fixm.aero/flight/4.2" schemaLocation="../flight/flightdata/FlightData.xsd"/>
	<xs:import namespace="http://www.fixm.aero/base/4.2" schemaLocation="../base/Measures.xsd"/>
	<xs:import namespace="http://www.fixm.aero/base/4.2" schemaLocation="../base/Organization.xsd"/>
	<xs:import namespace="http://www.fixm.aero/base/4.2" schemaLocation="../base/Types.xsd"/>
	<xs:import namespace="http://www.fixm.aero/base/4.2" schemaLocation="../base/Extension.xsd"/>
	<xs:element name="LadrMessage" type="ladr:LadrMessageType">
		<xs:annotation>
			<xs:documentation>The LADR Message element is an entry point to the LADR FIXM model.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="LadrAltitudeSourceType">
		<xs:annotation>
			<xs:documentation>Code indicating the source of the altitude.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="BARO">
				<xs:annotation>
					<xs:documentation>his value indicates that the source is Barometric.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
			<xs:enumeration value="GNSS">
				<xs:annotation>
					<xs:documentation>This value indicates that the source is the Global Navigation Satellite System.</xs:documentation>
				</xs:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LadrDistressValidationCodeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="FALSE_ACTIVATION"/>
			<xs:enumeration value="GENUINE"/>
			<xs:enumeration value="UNDETERMINED"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LadrMessageTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LADR_EVENT_MESSAGE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="LadrEventType">
		<xs:sequence>
			<xs:element name="identifier" type="fb:UniversallyUniqueIdentifierType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="eventIssuedTime" type="fb:TimeType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="eventValidatedTime" type="fb:TimeType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="contributorCode" type="fb:PersonOrOrganizationType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="distressValidationCode" type="ladr:LadrDistressValidationCodeType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="dataSource" type="fb:CharacterStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="adtActivationMethod" type="fb:CharacterStringType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="activationCodeInterpretation" type="fb:CharacterStringType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="eventTransittingFIRTime" type="fb:TimeType" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LadrLastPositionReportExtensionType">
		<xs:complexContent>
			<xs:extension base="fb:LastPositionReportExtensionType">
				<xs:sequence>
					<xs:element name="altitude" type="fb:AltitudeType" minOccurs="1" maxOccurs="1"/>
					<xs:element name="altitudeSource" type="ladr:LadrAltitudeSourceType" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Source of the altitude.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="horizontalAccuracy" type="fb:DistanceType" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>The difference between the horizontal coordinates of the aircraft measured by the ADT system and its true position referenced to the same geodetic datum expressed as a circular error at 95 percent probability.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="groundSpeed" type="fb:GroundSpeedType" minOccurs="1" maxOccurs="1"/>
					<xs:element name="heading" type="fb:BearingType" minOccurs="0" maxOccurs="1"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LadrMessageType">
		<xs:annotation>
			<xs:documentation>[TO BE REVISED] A communication sent from one location to another and comprising an integral number of fields. [ICAO Doc 9426]. </xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="uniqueMessageIdentifier" type="fb:UniversallyUniqueIdentifierType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>A unique message identifier for LADR messages.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timestamp" type="fb:TimeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The time and date that the communication was sent.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="receiptTime" type="fb:TimeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Date and time of receipt.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="type" type="ladr:LadrMessageTypeType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Represents the type of message.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ladrEvent" type="ladr:LadrEventType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="flight" type="fx:FlightType" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>The flight that the LADR Message is about.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LadrSurvivalCapabilitiesExtensionType">
		<xs:complexContent>
			<xs:extension base="fb:SurvivalCapabilitiesExtensionType">
				<xs:sequence>
					<xs:element name="carriedEltHexId" type="fb:CharacterStringType" minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>Carried ELT devices.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== eurocontrol-ladr/ladrApplicationMessages/samples/LadrEventUploadValidationMessage_Example1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ladr:LadrMessage xmlns:ladr="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0" xmlns:fx="http://www.fixm.aero/flight/4.2" xmlns:fb="http://www.fixm.aero/base/4.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.eurocontrol.int/nm/fixm/app/ladr/1.0 ..\schemas\\ladrEventUploadValidationMessage\\ladrmessage\LadrMessage.xsd">
	<ladr:timestamp>2022-01-19T06:00:10Z</ladr:timestamp>
	<ladr:receiptTime>2022-01-19T06:00:11Z</ladr:receiptTime>
	<ladr:type>LADR_EVENT_UPLOAD_VALIDATION_MESSAGE</ladr:type>
	<ladr:messageValidationStatus>VALID</ladr:messageValidationStatus>
	<ladr:referencedMessageIdentifier codeSpace="urn:uuid">49936b64-ff6d-4a7f-b633-67a60d869d1d</ladr:referencedMessageIdentifier>
	<ladr:ladrEvent>
		<ladr:identifier codeSpace="urn:uuid">a5e688eb-384a-4229-97b6-c29d39bf9069</ladr:identifier>
		<ladr:contributorCode>
			<fb:identifier>ABC</fb:identifier>
		</ladr:contributorCode>
	</ladr:ladrEvent>
</ladr:LadrMessage>
